version: '3.8'

services:
  postgres:
    image: docker.io/library/postgres:15-alpine
    environment:
      POSTGRES_USER: loganalyzer
      POSTGRES_PASSWORD: securepassword123
      POSTGRES_DB: loganalyzer
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - loganalyzer-network

  redis:
    image: docker.io/library/redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - loganalyzer-network

  ollama:
    image: docker.io/ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - loganalyzer-network
    # Podman doesn't support GPU devices in compose yet
    # For GPU support, run ollama separately with:
    # podman run -d --name ollama --device nvidia.com/gpu=all docker.io/ollama/ollama

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+asyncpg://loganalyzer:securepassword123@postgres/loganalyzer
      REDIS_URL: redis://redis:6379
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-change-in-production}
      VIRUSTOTAL_API_KEY: ${VIRUSTOTAL_API_KEY}
      ABUSEIPDB_API_KEY: ${ABUSEIPDB_API_KEY}
      OLLAMA_HOST: http://ollama:11434
    volumes:
      - ./backend:/app:Z
      - /tmp/uploads:/tmp/uploads:Z
      - /tmp/exports:/tmp/exports:Z
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - ollama
    networks:
      - loganalyzer-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    volumes:
      - ./frontend:/app:Z
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - loganalyzer-network
    command: npm run dev

  nginx:
    image: docker.io/library/nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:Z
      - ./nginx/ssl:/etc/nginx/ssl:Z
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - loganalyzer-network

volumes:
  postgres_data:
  ollama_data:

networks:
  loganalyzer-network:
    driver: bridge